version: '3.8'

services:
  web:
    build: .
    container_name: ctf-lfi
    ports:
      - "3080:5008"
      - "3022:22"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    networks:
      - ctf-network

networks:
  ctf-network:
    driver: bridge
